spin_manifest_version = "1"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
name = "wasmio"
trigger = { type = "tcpline" }
version = "0.1.0"

[[component]]
id = "test"
source = "target/wasm32-wasi/release/guest.wasm"
[component.trigger]
port = 8089
[component.build]
command = "cargo build --target wasm32-wasi --release"
